# Generated by Django 4.1.7 on 2023-03-11 07:12

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sulg",
            field=autoslug.fields.AutoSlugField(editable=False, populate_from="title"),
        ),
    ]
