# Generated by Django 4.1.7 on 2023-03-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_product_sulg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sulg",
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
